require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'flighteno' do

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'FaceDetectorMLKit'
  ]

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  

  target 'flightenoTests' do
    inherit! :complete
    # Pods for testing

    
    # permissions_path = '../node_modules/react-native-permissions/ios'
    # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
    # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
    # pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    # pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
    # pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
    # pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"
    # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    # pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts"
    # pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
    # pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    # pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
    # pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
    # pod 'Permission-Motion', :path => "#{permissions_path}/Motion"
    # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
    # pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    # pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"
    # pod 'Permission-Reminders', :path => "#{permissions_path}/Reminders"
    # pod 'Permission-Siri', :path => "#{permissions_path}/Siri"
    # pod 'Permission-SpeechRecognition', :path => "#{permissions_path}/SpeechRecognition"
    # pod 'Permission-StoreKit', :path => "#{permissions_path}/StoreKit"

  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
  #     end
  #   end
  # end
  # post_install do |installer|
  #   react_native_post_install(installer)

  #   # Apple Silicon builds require a library path tweak for Swift library discovery or "symbol not found" for swift things
  #   installer.aggregate_targets.each do |aggregate_target| 
  #     aggregate_target.user_project.native_targets.each do |target|
  #       target.build_configurations.each do |config|
  #         config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
  #       end
  #     end
  #     aggregate_target.user_project.save
  #   end

     # Flipper requires a crude patch to bump up iOS deployment target, or "error: thread-local storage is not supported for the current target"
    # I'm not aware of any other way to fix this one other than bumping iOS deployment target to match react-native (iOS 11 now)
    # installer.pods_project.targets.each do |target|
    #   target.build_configurations.each do |config|
    #     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    #    end
    # end

    # ...but if you bump iOS deployment target, Flipper barfs again "Time.h:52:17: error: typedef redefinition with different types"
    # We need to make one crude patch to RCT-Folly - set `__IPHONE_10_0` to our iOS target + 1
    # https://github.com/facebook/flipper/issues/834 - 84 comments and still going...
  #   `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' #{installer.sandbox.root}/RCT-Folly/folly/portability/Time.h`
  # end
  post_install do |installer|
    react_native_post_install(installer)
  end
end